python fasttext_lstm19_cudnn_prep_repeat_expand.py
python fasttext_lstm20_cudnn_prep_repeat_expand.py
python fasttext_lstm21_cudnn_prep_repeat_expand.py
python fasttext_lstm22_cudnn_prep_repeat_expand.py
python fasttext_lstm24_cudnn_prep_repeat_expand.py
python fasttext_lstm23_cudnn_prep_repeat_expand_mlp.py
python fasttext_lstm25_cudnn_prep_repeat_expand_conv.py
